Ajout du thème Limelight
FranckRJ/RespawnIRC pull request #48
Opened 2016-09-30 21:00 UTC by Ginkyway

2016-09-30 22:37 UTC, FranckRJ requested changes
Voilà, si t'as pas envie de le faire je le ferais à ta place, je voulais juste tester les reviews.

Au passage, j'apprécierais que tu trouve un nom français pour ton thème.

2016-09-30 22:37 UTC, LEpigeon888 commented on themes/Limelight/style.css
> +QTabBar::tab
Remplace ça par `QTabWidget#tabListForTopics QTabBar::tab`, ton code actuel modifie aussi les onglets sur la fenêtre préférence, c'est pas cool.
Tu dois le faire pour tous les `QTabBar::tab` et pas seulement celui auquel je me réfère.

2016-09-30 22:37 UTC, LEpigeon888 commented on themes/Limelight/style.css
> +}
C'est pas obligatoire mais si les boutons pouvaient se modifier selon leur état ça serait vraiment cool, regarde le thème Grisaille si je dis pas de connerie j'avais géré tous les cas (https://github.com/LEpigeon888/RespawnIRC/blob/master/themes/Grisaille/style.css#L139-L158).

EDIT: Au lieu de modifier le background pour les boutons-image tu peux peut-être regarder du côté de la modification des bordures, au passage la propriété `outline: none;` pourra t'être utile.

2016-10-01 04:35 UTC, Ginkyway commented on themes/Limelight/style.css
> +}
J'ai rien trouvé de joli pour les boutons, au pire je ferai un autre PR plus tard.

2016-10-01 09:38 UTC, FranckRJ requested changes

2016-10-01 09:38 UTC, LEpigeon888 commented on themes/Limette/style.css
> +}
Je sais pas si c'est voulu, mais ce code modifiera toutes les listes (même celles des thèmes, pseudos ignoré, etc). Si tu veux modifier uniquement la liste des topics tu dois utiliser `QTabWidget#tabListForTopics QListView`, idem pour le code à la ligne 8.

Tu peux faire de même pour le QTextBrowser, actuellement il est uniquement utilisé pour affiché les messages, mais peut-être qu'un jour il sera utilisé pour autre chose.

2016-10-01 09:38 UTC, LEpigeon888 commented on themes/Limette/style.css
> +}
Pas de spécialisation pour focus, hover et disabled pour le bouton d'envoi ? C'est un oublie ou un choix ?

Focus est peut-être pas forcément utile, parce que de base il y a un outline quand le bouton est focus (je crois), hover c'est juste pour le style donc au pire osef, mais disabled (enfin plutôt `!enabled`) est important car il informe l'utilisateur qu'un message est entrain d'être envoyé.

2016-10-01 16:04 UTC, Ginkyway commented on themes/Limette/style.css
> +}
le qtextbrowser tu peux le faire toi-même je connais pas le nom de la classe

2016-10-01 16:05 UTC, Ginkyway commented on themes/Limette/style.css
> +}
focus est par défaut, hover est présent dans le css, disabled est par défaut (texte grisé)

2016-10-01 16:26 UTC, LEpigeon888 commented on themes/Limette/style.css
> +}
Bah c'est `QTextBrowser`, donc `QTabWidget#tabListForTopics QTextBrowser`, comme pour la `QListView`

2016-10-01 16:32 UTC, FranckRJ approved these changes

2016-10-01 16:36 UTC, merged